apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "podcast-app.fullname" . }}-backend-config
data:
  {{- range $key, $value := .Values.backend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
