apiVersion: v1
kind: Secret
metadata:
  name: {{ include "podcast-app.fullname" . }}-backend-secrets
type: Opaque
stringData:
  {{- range $key, $value := .Values.backend.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
