version: '3.9'
services:
  backend:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.backend
    ports:
      - '3000:3000'
    env_file:
      - ../../apps/backend/.env.development
  admin:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.admin
    ports:
      - '5173:5173'
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: podcast_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  redis:
    image: redis:7
    ports:
      - '6379:6379'
