version: '3.9'
services:
  backend:
    build:
      context: ../..
      dockerfile: apps/backend/Dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/podcast_app?schema=public
    depends_on:
      - postgres
    command: sh -c "yarn prisma:migrate:deploy && yarn start:prod"
  admin:
    build:
      context: ../..
      dockerfile: apps/admin/Dockerfile
    ports:
      - '5173:5173'
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: podcast_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  redis:
    image: redis:7
    ports:
      - '6379:6379'
