backend:
  replicas: 2
  env:
    NODE_ENV: staging
    PORT: "3300"
  secrets:
    DATABASE_URL: postgresql://postgres:postgres@postgres:5432/podcast_app?schema=public
    REDIS_URL: redis://redis:6379
    JWT_ACCESS_SECRET: staging-access-secret
    JWT_REFRESH_SECRET: staging-refresh-secret
    S3_ENDPOINT: https://s3-staging.podcast-app.com
    S3_ACCESS_KEY: CHANGE_ME
    S3_SECRET_KEY: CHANGE_ME
    ADMIN_TENANT_NAME: Default Tenant
    ADMIN_TENANT_SLUG: default
    ADMIN_EMAIL: admin@podcast.dev
    ADMIN_NAME: Platform Admin
    ADMIN_PASSWORD: changeme
    ADMIN_PASSWORD_SALT_ROUNDS: "12"
