replicaCount: 3

backend:
  env:
    LOG_LEVEL: "warn"

  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

admin:
  replicaCount: 3

ingress:
  hosts:
    - host: api.podcast-app.com
      paths:
        - path: /
          pathType: Prefix
          service: backend
          port: 3300
    - host: admin.podcast-app.com
      paths:
        - path: /
          pathType: Prefix
          service: admin
          port: 5175
