backend:
  secrets:
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/podcast_app?schema=public"
    REDIS_URL: "redis://redis:6379"
    CORS_ORIGINS: "http://localhost:5175,http://localhost:19005"
    S3_ENDPOINT: "http://minio:9000"
    S3_ACCESS_KEY: "minioadmin"
    S3_SECRET_KEY: "minioadmin"
    S3_BUCKET: "podcast-uploads-dev"

ingress:
  hosts:
    - host: api.podcast-app.local
      paths:
        - path: /
          pathType: Prefix
          service: backend
          port: 3300
    - host: admin.podcast-app.local
      paths:
        - path: /
          pathType: Prefix
          service: admin
          port: 5175
