// This file is auto-generated by scripts/sync-prisma-enums.js. Do not edit manually.

export enum AnalyticsEventType {
  PODCAST_PLAY = 'PODCAST_PLAY',
  PODCAST_COMPLETE = 'PODCAST_COMPLETE',
  PODCAST_FOLLOW = 'PODCAST_FOLLOW',
  PODCAST_SHARE = 'PODCAST_SHARE',
  STREAM_JOIN = 'STREAM_JOIN',
}

export const AnalyticsEventTypeValues = ['PODCAST_PLAY', 'PODCAST_COMPLETE', 'PODCAST_FOLLOW', 'PODCAST_SHARE', 'STREAM_JOIN'] as const;
