// This file is auto-generated by scripts/sync-prisma-enums.js. Do not edit manually.

export enum NotificationType {
  EPISODE_PUBLISHED = 'EPISODE_PUBLISHED',
  COMMENT_REPLY = 'COMMENT_REPLY',
  SYSTEM = 'SYSTEM',
}

export const NotificationTypeValues = ['EPISODE_PUBLISHED', 'COMMENT_REPLY', 'SYSTEM'] as const;
