// This file is auto-generated by scripts/sync-prisma-enums.js. Do not edit manually.

export enum StreamStatus {
  SCHEDULED = 'SCHEDULED',
  LIVE = 'LIVE',
  ENDED = 'ENDED',
  CANCELLED = 'CANCELLED',
}

export const StreamStatusValues = ['SCHEDULED', 'LIVE', 'ENDED', 'CANCELLED'] as const;
