// This file is auto-generated by scripts/sync-prisma-enums.js. Do not edit manually.

export enum UserRole {
  ADMIN = 'ADMIN',
  EDITOR = 'EDITOR',
  CREATOR = 'CREATOR',
  LISTENER = 'LISTENER',
}

export const UserRoleValues = ['ADMIN', 'EDITOR', 'CREATOR', 'LISTENER'] as const;
