name: Admin CI

on:
  push:
    branches:
      - main
      - develop
      - "frontend/**"
  pull_request:
    branches:
      - main
      - develop
      - "frontend/**"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: podcast-admin

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn workspace @podcast-app/admin lint

      - name: Test
        run: yarn workspace @podcast-app/admin test --passWithNoTests

      - name: Build
        run: yarn workspace @podcast-app/admin build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/admin/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Configure AWS Credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync Admin Build to S3
        if: github.ref == 'refs/heads/main'
        run: aws s3 sync apps/admin/dist s3://${{ secrets.ADMIN_S3_BUCKET }}/ --delete
