name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment (staging|production)"
        required: true
        default: staging
  push:
    tags:
      - "v*.*.*"

jobs:
  init-db:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      BACKEND_IMAGE: podcast-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "latest"

      - name: Configure kubeconfig
        run: |
          echo "${KUBE_CONFIG}" > $HOME/.kubeconfig
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Apply Prisma Migrations
        run: |
          kubectl --kubeconfig $HOME/.kubeconfig run prisma-migrate --rm -i --restart=Never \
            --image=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.BACKEND_IMAGE }}:latest \
            --env="DATABASE_URL=${{ secrets.DATABASE_URL }}" \
            --command -- yarn prisma migrate deploy

  deploy:
    runs-on: ubuntu-latest
    needs: init-db
    env:
      REGISTRY: ghcr.io
      BACKEND_IMAGE: podcast-backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: "latest"

      - name: Configure kubeconfig
        run: echo "${KUBE_CONFIG}" > $HOME/.kubeconfig
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Helm Upgrade
        run: |
          helm upgrade --install podcast-app infra/helm/podcast-app \
            -f infra/helm/podcast-app/values.yaml \
            --set backend.image.repository=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.BACKEND_IMAGE }} \
            --set backend.image.tag=latest
        env:
          KUBECONFIG: $HOME/.kubeconfig

      - name: Verify Readiness
        run: curl -f https://${{ secrets.HEALTHCHECK_HOST }}/api/health/readiness
        env:
          KUBECONFIG: $HOME/.kubeconfig
